/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MalekWindowLogin (void);
GtkWidget* create_MalekMhatliWAdmin (void);
GtkWidget* create_MalekMhatliWEntraineur (void);
GtkWidget* create_MalekMhatliWModifier5 (void);
GtkWidget* create_MalekMhatliWindowSupp5 (void);
GtkWidget* create_MalekMhatliWindowAjout5 (void);
GtkWidget* create_MalekMhatliWindowCherche5 (void);
GtkWidget* create_RaedWindowMembre (void);
GtkWidget* create_MalekMhatliWindInscritCours (void);
