/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_MalekWindowLogin (void)
{
  GtkWidget *MalekWindowLogin;
  GtkWidget *MalekFixedLogin;
  GtkWidget *MalekCentryIdentifiant;
  GtkWidget *MalekCentryPassword;
  GtkWidget *MalekButtonConnexion;
  GtkWidget *MalekLabelIdentifiant;
  GtkWidget *MalekLabelPassword;

  MalekWindowLogin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MalekWindowLogin), _("Connexion"));
  gtk_window_set_position (GTK_WINDOW (MalekWindowLogin), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (MalekWindowLogin), 400, 300);

  MalekFixedLogin = gtk_fixed_new ();
  gtk_widget_show (MalekFixedLogin);
  gtk_container_add (GTK_CONTAINER (MalekWindowLogin), MalekFixedLogin);

  MalekCentryIdentifiant = gtk_entry_new ();
  gtk_widget_show (MalekCentryIdentifiant);
  gtk_fixed_put (GTK_FIXED (MalekFixedLogin), MalekCentryIdentifiant, 352, 128);
  gtk_widget_set_size_request (MalekCentryIdentifiant, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (MalekCentryIdentifiant), 8226);

  MalekCentryPassword = gtk_entry_new ();
  gtk_widget_show (MalekCentryPassword);
  gtk_fixed_put (GTK_FIXED (MalekFixedLogin), MalekCentryPassword, 352, 208);
  gtk_widget_set_size_request (MalekCentryPassword, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (MalekCentryPassword), 8226);

  MalekButtonConnexion = gtk_button_new_with_mnemonic (_("Connexion\n"));
  gtk_widget_show (MalekButtonConnexion);
  gtk_fixed_put (GTK_FIXED (MalekFixedLogin), MalekButtonConnexion, 256, 312);
  gtk_widget_set_size_request (MalekButtonConnexion, 152, 29);

  MalekLabelIdentifiant = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (MalekLabelIdentifiant);
  gtk_fixed_put (GTK_FIXED (MalekFixedLogin), MalekLabelIdentifiant, 176, 128);
  gtk_widget_set_size_request (MalekLabelIdentifiant, 120, 25);
  gtk_misc_set_alignment (GTK_MISC (MalekLabelIdentifiant), 0.5, 0.73);

  MalekLabelPassword = gtk_label_new (_("Mot de passe:\n"));
  gtk_widget_show (MalekLabelPassword);
  gtk_fixed_put (GTK_FIXED (MalekFixedLogin), MalekLabelPassword, 192, 216);
  gtk_widget_set_size_request (MalekLabelPassword, 104, 17);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MalekWindowLogin, MalekWindowLogin, "MalekWindowLogin");
  GLADE_HOOKUP_OBJECT (MalekWindowLogin, MalekFixedLogin, "MalekFixedLogin");
  GLADE_HOOKUP_OBJECT (MalekWindowLogin, MalekCentryIdentifiant, "MalekCentryIdentifiant");
  GLADE_HOOKUP_OBJECT (MalekWindowLogin, MalekCentryPassword, "MalekCentryPassword");
  GLADE_HOOKUP_OBJECT (MalekWindowLogin, MalekButtonConnexion, "MalekButtonConnexion");
  GLADE_HOOKUP_OBJECT (MalekWindowLogin, MalekLabelIdentifiant, "MalekLabelIdentifiant");
  GLADE_HOOKUP_OBJECT (MalekWindowLogin, MalekLabelPassword, "MalekLabelPassword");

  return MalekWindowLogin;
}

GtkWidget*
create_MalekMhatliWAdmin (void)
{
  GtkWidget *MalekMhatliWAdmin;
  GtkWidget *MalekMhatlinotebook1;
  GtkWidget *empty_notebook_page;
  GtkWidget *MalekMhatliWMemebers;
  GtkWidget *MalekMhatliWCoach;
  GtkWidget *raednotebook10;
  GtkWidget *fixed;
  GtkWidget *raedentryrecherche;
  GtkWidget *raedwindowcourrecherche;
  GtkWidget *raedtreeviewrecherche;
  GtkWidget *raedlabelbienvenue1;
  GtkWidget *raedbuttonrecherche;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image34;
  GtkWidget *label237;
  GtkWidget *raedlabelrecherche;
  GtkWidget *fixed33;
  GtkWidget *raedentryid1;
  GtkWidget *raedentrynom1;
  GtkWidget *raedentrycentre1;
  GtkObject *raedspinbuttonday1_adj;
  GtkWidget *raedspinbuttonday1;
  GtkObject *raedspinbuttonmonth1_adj;
  GtkWidget *raedspinbuttonmonth1;
  GtkObject *raedspinbuttonyear1_adj;
  GtkWidget *raedspinbuttonyear1;
  GtkWidget *raedlabeldate1;
  GtkWidget *raedlabelidantifiant;
  GtkWidget *raedlabelspecialit__1;
  GtkWidget *raedlabelcentre1;
  GtkWidget *raedlabel321;
  GtkWidget *raedlabelnom1;
  GtkWidget *raedradiobutton10;
  GSList *raedradiobutton10_group = NULL;
  GtkWidget *raedradiobutton11;
  GtkWidget *raedbutton42;
  GtkWidget *raedalignmentajouter1;
  GtkWidget *hbox28;
  GtkWidget *image36;
  GtkWidget *label252;
  GtkWidget *raedcomboboxentryspecialit__1;
  GtkWidget *raedlabelajout;
  GtkWidget *fixed34;
  GtkObject *raedspinbuttonday2_adj;
  GtkWidget *raedspinbuttonday2;
  GtkObject *raedspinbuttonmonth2_adj;
  GtkWidget *raedspinbuttonmonth2;
  GtkObject *raedspinbuttonyear2_adj;
  GtkWidget *raedspinbuttonyear2;
  GtkWidget *raedentrynom2;
  GtkWidget *raedentryid2;
  GtkWidget *raedentrycour2;
  GtkWidget *raedlabeldate2;
  GtkWidget *raedlabelspecialit__2;
  GtkWidget *raedlabelcentre2;
  GtkWidget *raedlabelnom2;
  GtkWidget *raedlabelid2;
  GtkWidget *raedcomboboxentryspecialit__2;
  GtkWidget *raedbutton45;
  GtkWidget *raedalignmentmodifier2;
  GtkWidget *hbox31;
  GtkWidget *image39;
  GtkWidget *label258;
  GtkWidget *raedlabelbienvenue2;
  GtkWidget *raedlabelrmodifier;
  GtkWidget *fixed35;
  GtkWidget *raedentryid3;
  GtkWidget *raedlabelid3;
  GtkWidget *raedbutton43;
  GtkWidget *raedalignmentsupprimer3;
  GtkWidget *hbox29;
  GtkWidget *image37;
  GtkWidget *label255;
  GtkWidget *raedlabelbienvenue3;
  GtkWidget *raedlabelrechercher;
  GtkWidget *MalekMhatliWCourseSportif;
  GtkWidget *MalekMhatliWEquipement;
  GtkWidget *MalekMhatliWCenters;
  GtkWidget *MalekMhatliWEvents;

  MalekMhatliWAdmin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MalekMhatliWAdmin), _("Espace-Admin"));

  MalekMhatlinotebook1 = gtk_notebook_new ();
  gtk_widget_show (MalekMhatlinotebook1);
  gtk_container_add (GTK_CONTAINER (MalekMhatliWAdmin), MalekMhatlinotebook1);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (MalekMhatlinotebook1), empty_notebook_page);

  MalekMhatliWMemebers = gtk_label_new (_("Membres"));
  gtk_widget_show (MalekMhatliWMemebers);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (MalekMhatlinotebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (MalekMhatlinotebook1), 0), MalekMhatliWMemebers);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (MalekMhatlinotebook1), empty_notebook_page);

  MalekMhatliWCoach = gtk_label_new (_("Entraineurs"));
  gtk_widget_show (MalekMhatliWCoach);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (MalekMhatlinotebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (MalekMhatlinotebook1), 1), MalekMhatliWCoach);

  raednotebook10 = gtk_notebook_new ();
  gtk_widget_show (raednotebook10);
  gtk_container_add (GTK_CONTAINER (MalekMhatlinotebook1), raednotebook10);

  fixed = gtk_fixed_new ();
  gtk_widget_show (fixed);
  gtk_container_add (GTK_CONTAINER (raednotebook10), fixed);

  raedentryrecherche = gtk_entry_new ();
  gtk_widget_show (raedentryrecherche);
  gtk_fixed_put (GTK_FIXED (fixed), raedentryrecherche, 96, 56);
  gtk_widget_set_size_request (raedentryrecherche, 216, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (raedentryrecherche), 8226);

  raedwindowcourrecherche = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (raedwindowcourrecherche);
  gtk_fixed_put (GTK_FIXED (fixed), raedwindowcourrecherche, 96, 160);
  gtk_widget_set_size_request (raedwindowcourrecherche, 544, 304);

  raedtreeviewrecherche = gtk_tree_view_new ();
  gtk_widget_show (raedtreeviewrecherche);
  gtk_container_add (GTK_CONTAINER (raedwindowcourrecherche), raedtreeviewrecherche);
  gtk_widget_set_size_request (raedtreeviewrecherche, 344, 312);

  raedlabelbienvenue1 = gtk_label_new (_("Bienvenue dans votre Espace-Admin"));
  gtk_widget_show (raedlabelbienvenue1);
  gtk_fixed_put (GTK_FIXED (fixed), raedlabelbienvenue1, 216, 8);
  gtk_widget_set_size_request (raedlabelbienvenue1, 320, 41);

  raedbuttonrecherche = gtk_button_new ();
  gtk_widget_show (raedbuttonrecherche);
  gtk_fixed_put (GTK_FIXED (fixed), raedbuttonrecherche, 424, 56);
  gtk_widget_set_size_request (raedbuttonrecherche, 208, 56);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (raedbuttonrecherche), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image34 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox26), image34, FALSE, FALSE, 0);

  label237 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label237);
  gtk_box_pack_start (GTK_BOX (hbox26), label237, FALSE, FALSE, 0);

  raedlabelrecherche = gtk_label_new (_("Rechercher"));
  gtk_widget_show (raedlabelrecherche);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (raednotebook10), gtk_notebook_get_nth_page (GTK_NOTEBOOK (raednotebook10), 0), raedlabelrecherche);

  fixed33 = gtk_fixed_new ();
  gtk_widget_show (fixed33);
  gtk_container_add (GTK_CONTAINER (raednotebook10), fixed33);

  raedentryid1 = gtk_entry_new ();
  gtk_widget_show (raedentryid1);
  gtk_fixed_put (GTK_FIXED (fixed33), raedentryid1, 320, 72);
  gtk_widget_set_size_request (raedentryid1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (raedentryid1), 8226);

  raedentrynom1 = gtk_entry_new ();
  gtk_widget_show (raedentrynom1);
  gtk_fixed_put (GTK_FIXED (fixed33), raedentrynom1, 320, 120);
  gtk_widget_set_size_request (raedentrynom1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (raedentrynom1), 8226);

  raedentrycentre1 = gtk_entry_new ();
  gtk_widget_show (raedentrycentre1);
  gtk_fixed_put (GTK_FIXED (fixed33), raedentrycentre1, 320, 312);
  gtk_widget_set_size_request (raedentrycentre1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (raedentrycentre1), 8226);

  raedspinbuttonday1_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  raedspinbuttonday1 = gtk_spin_button_new (GTK_ADJUSTMENT (raedspinbuttonday1_adj), 1, 0);
  gtk_widget_show (raedspinbuttonday1);
  gtk_fixed_put (GTK_FIXED (fixed33), raedspinbuttonday1, 320, 208);
  gtk_widget_set_size_request (raedspinbuttonday1, 60, 27);

  raedspinbuttonmonth1_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  raedspinbuttonmonth1 = gtk_spin_button_new (GTK_ADJUSTMENT (raedspinbuttonmonth1_adj), 1, 0);
  gtk_widget_show (raedspinbuttonmonth1);
  gtk_fixed_put (GTK_FIXED (fixed33), raedspinbuttonmonth1, 392, 208);
  gtk_widget_set_size_request (raedspinbuttonmonth1, 60, 27);

  raedspinbuttonyear1_adj = gtk_adjustment_new (1, 0, 2030, 1, 10, 10);
  raedspinbuttonyear1 = gtk_spin_button_new (GTK_ADJUSTMENT (raedspinbuttonyear1_adj), 1, 0);
  gtk_widget_show (raedspinbuttonyear1);
  gtk_fixed_put (GTK_FIXED (fixed33), raedspinbuttonyear1, 464, 208);
  gtk_widget_set_size_request (raedspinbuttonyear1, 60, 27);

  raedlabeldate1 = gtk_label_new (_("Date de expiration :"));
  gtk_widget_show (raedlabeldate1);
  gtk_fixed_put (GTK_FIXED (fixed33), raedlabeldate1, 128, 208);
  gtk_widget_set_size_request (raedlabeldate1, 144, 32);

  raedlabelidantifiant = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (raedlabelidantifiant);
  gtk_fixed_put (GTK_FIXED (fixed33), raedlabelidantifiant, 112, 72);
  gtk_widget_set_size_request (raedlabelidantifiant, 136, 24);

  raedlabelspecialit__1 = gtk_label_new (_("Sp\303\251cialit\303\251 :"));
  gtk_widget_show (raedlabelspecialit__1);
  gtk_fixed_put (GTK_FIXED (fixed33), raedlabelspecialit__1, 112, 256);
  gtk_widget_set_size_request (raedlabelspecialit__1, 120, 32);

  raedlabelcentre1 = gtk_label_new (_("Centre :"));
  gtk_widget_show (raedlabelcentre1);
  gtk_fixed_put (GTK_FIXED (fixed33), raedlabelcentre1, 80, 304);
  gtk_widget_set_size_request (raedlabelcentre1, 168, 24);

  raedlabel321 = gtk_label_new (_("niveau :"));
  gtk_widget_show (raedlabel321);
  gtk_fixed_put (GTK_FIXED (fixed33), raedlabel321, 136, 352);
  gtk_widget_set_size_request (raedlabel321, 57, 17);

  raedlabelnom1 = gtk_label_new (_("Nom :"));
  gtk_widget_show (raedlabelnom1);
  gtk_fixed_put (GTK_FIXED (fixed33), raedlabelnom1, 120, 120);
  gtk_widget_set_size_request (raedlabelnom1, 88, 32);

  raedradiobutton10 = gtk_radio_button_new_with_mnemonic (NULL, _("debutant"));
  gtk_widget_show (raedradiobutton10);
  gtk_fixed_put (GTK_FIXED (fixed33), raedradiobutton10, 320, 352);
  gtk_widget_set_size_request (raedradiobutton10, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (raedradiobutton10), raedradiobutton10_group);
  raedradiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (raedradiobutton10));

  raedradiobutton11 = gtk_radio_button_new_with_mnemonic (NULL, _("professionnel"));
  gtk_widget_show (raedradiobutton11);
  gtk_fixed_put (GTK_FIXED (fixed33), raedradiobutton11, 432, 352);
  gtk_widget_set_size_request (raedradiobutton11, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (raedradiobutton11), raedradiobutton10_group);
  raedradiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (raedradiobutton11));

  raedbutton42 = gtk_button_new ();
  gtk_widget_show (raedbutton42);
  gtk_fixed_put (GTK_FIXED (fixed33), raedbutton42, 536, 80);
  gtk_widget_set_size_request (raedbutton42, 184, 48);

  raedalignmentajouter1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (raedalignmentajouter1);
  gtk_container_add (GTK_CONTAINER (raedbutton42), raedalignmentajouter1);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (raedalignmentajouter1), hbox28);

  image36 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox28), image36, FALSE, FALSE, 0);

  label252 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label252);
  gtk_box_pack_start (GTK_BOX (hbox28), label252, FALSE, FALSE, 0);

  raedcomboboxentryspecialit__1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (raedcomboboxentryspecialit__1);
  gtk_fixed_put (GTK_FIXED (fixed33), raedcomboboxentryspecialit__1, 320, 256);
  gtk_widget_set_size_request (raedcomboboxentryspecialit__1, 157, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (raedcomboboxentryspecialit__1), _("fitness"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (raedcomboboxentryspecialit__1), _("yoga"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (raedcomboboxentryspecialit__1), _("cardio "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (raedcomboboxentryspecialit__1), _("boxe"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (raedcomboboxentryspecialit__1), _("karate"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (raedcomboboxentryspecialit__1), _("musculation "));

  raedlabelajout = gtk_label_new (_("Ajouter"));
  gtk_widget_show (raedlabelajout);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (raednotebook10), gtk_notebook_get_nth_page (GTK_NOTEBOOK (raednotebook10), 1), raedlabelajout);

  fixed34 = gtk_fixed_new ();
  gtk_widget_show (fixed34);
  gtk_container_add (GTK_CONTAINER (raednotebook10), fixed34);

  raedspinbuttonday2_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  raedspinbuttonday2 = gtk_spin_button_new (GTK_ADJUSTMENT (raedspinbuttonday2_adj), 1, 0);
  gtk_widget_show (raedspinbuttonday2);
  gtk_fixed_put (GTK_FIXED (fixed34), raedspinbuttonday2, 184, 224);
  gtk_widget_set_size_request (raedspinbuttonday2, 60, 27);

  raedspinbuttonmonth2_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  raedspinbuttonmonth2 = gtk_spin_button_new (GTK_ADJUSTMENT (raedspinbuttonmonth2_adj), 1, 0);
  gtk_widget_show (raedspinbuttonmonth2);
  gtk_fixed_put (GTK_FIXED (fixed34), raedspinbuttonmonth2, 256, 224);
  gtk_widget_set_size_request (raedspinbuttonmonth2, 60, 27);

  raedspinbuttonyear2_adj = gtk_adjustment_new (1, 0, 2026, 1, 10, 10);
  raedspinbuttonyear2 = gtk_spin_button_new (GTK_ADJUSTMENT (raedspinbuttonyear2_adj), 1, 0);
  gtk_widget_show (raedspinbuttonyear2);
  gtk_fixed_put (GTK_FIXED (fixed34), raedspinbuttonyear2, 328, 224);
  gtk_widget_set_size_request (raedspinbuttonyear2, 60, 27);

  raedentrynom2 = gtk_entry_new ();
  gtk_widget_show (raedentrynom2);
  gtk_fixed_put (GTK_FIXED (fixed34), raedentrynom2, 184, 176);
  gtk_widget_set_size_request (raedentrynom2, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (raedentrynom2), 8226);

  raedentryid2 = gtk_entry_new ();
  gtk_widget_show (raedentryid2);
  gtk_fixed_put (GTK_FIXED (fixed34), raedentryid2, 184, 128);
  gtk_widget_set_size_request (raedentryid2, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (raedentryid2), 8226);

  raedentrycour2 = gtk_entry_new ();
  gtk_widget_show (raedentrycour2);
  gtk_fixed_put (GTK_FIXED (fixed34), raedentrycour2, 184, 312);
  gtk_widget_set_size_request (raedentrycour2, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (raedentrycour2), 8226);

  raedlabeldate2 = gtk_label_new (_("Date de expiration :"));
  gtk_widget_show (raedlabeldate2);
  gtk_fixed_put (GTK_FIXED (fixed34), raedlabeldate2, 32, 224);
  gtk_widget_set_size_request (raedlabeldate2, 144, 32);

  raedlabelspecialit__2 = gtk_label_new (_("Sp\303\251cialit\303\251 :"));
  gtk_widget_show (raedlabelspecialit__2);
  gtk_fixed_put (GTK_FIXED (fixed34), raedlabelspecialit__2, 16, 264);
  gtk_widget_set_size_request (raedlabelspecialit__2, 120, 32);

  raedlabelcentre2 = gtk_label_new (_("Centre :"));
  gtk_widget_show (raedlabelcentre2);
  gtk_fixed_put (GTK_FIXED (fixed34), raedlabelcentre2, 8, 312);
  gtk_widget_set_size_request (raedlabelcentre2, 120, 32);

  raedlabelnom2 = gtk_label_new (_("Nom :"));
  gtk_widget_show (raedlabelnom2);
  gtk_fixed_put (GTK_FIXED (fixed34), raedlabelnom2, 16, 176);
  gtk_widget_set_size_request (raedlabelnom2, 88, 32);

  raedlabelid2 = gtk_label_new (_("ID Cour :"));
  gtk_widget_show (raedlabelid2);
  gtk_fixed_put (GTK_FIXED (fixed34), raedlabelid2, 0, 136);
  gtk_widget_set_size_request (raedlabelid2, 136, 24);

  raedcomboboxentryspecialit__2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (raedcomboboxentryspecialit__2);
  gtk_fixed_put (GTK_FIXED (fixed34), raedcomboboxentryspecialit__2, 184, 264);
  gtk_widget_set_size_request (raedcomboboxentryspecialit__2, 157, 32);

  raedbutton45 = gtk_button_new ();
  gtk_widget_show (raedbutton45);
  gtk_fixed_put (GTK_FIXED (fixed34), raedbutton45, 120, 56);
  gtk_widget_set_size_request (raedbutton45, 184, 48);

  raedalignmentmodifier2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (raedalignmentmodifier2);
  gtk_container_add (GTK_CONTAINER (raedbutton45), raedalignmentmodifier2);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (raedalignmentmodifier2), hbox31);

  image39 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_box_pack_start (GTK_BOX (hbox31), image39, FALSE, FALSE, 0);

  label258 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label258);
  gtk_box_pack_start (GTK_BOX (hbox31), label258, FALSE, FALSE, 0);

  raedlabelbienvenue2 = gtk_label_new (_("Bienvenue dans votre Espace-Admin"));
  gtk_widget_show (raedlabelbienvenue2);
  gtk_fixed_put (GTK_FIXED (fixed34), raedlabelbienvenue2, 40, 8);
  gtk_widget_set_size_request (raedlabelbienvenue2, 320, 41);

  raedlabelrmodifier = gtk_label_new (_("Modifier"));
  gtk_widget_show (raedlabelrmodifier);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (raednotebook10), gtk_notebook_get_nth_page (GTK_NOTEBOOK (raednotebook10), 2), raedlabelrmodifier);

  fixed35 = gtk_fixed_new ();
  gtk_widget_show (fixed35);
  gtk_container_add (GTK_CONTAINER (raednotebook10), fixed35);

  raedentryid3 = gtk_entry_new ();
  gtk_widget_show (raedentryid3);
  gtk_fixed_put (GTK_FIXED (fixed35), raedentryid3, 248, 160);
  gtk_widget_set_size_request (raedentryid3, 200, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (raedentryid3), 8226);

  raedlabelid3 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (raedlabelid3);
  gtk_fixed_put (GTK_FIXED (fixed35), raedlabelid3, 0, 160);
  gtk_widget_set_size_request (raedlabelid3, 232, 56);

  raedbutton43 = gtk_button_new ();
  gtk_widget_show (raedbutton43);
  gtk_fixed_put (GTK_FIXED (fixed35), raedbutton43, 144, 320);
  gtk_widget_set_size_request (raedbutton43, 232, 48);

  raedalignmentsupprimer3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (raedalignmentsupprimer3);
  gtk_container_add (GTK_CONTAINER (raedbutton43), raedalignmentsupprimer3);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (raedalignmentsupprimer3), hbox29);

  image37 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_box_pack_start (GTK_BOX (hbox29), image37, FALSE, FALSE, 0);

  label255 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label255);
  gtk_box_pack_start (GTK_BOX (hbox29), label255, FALSE, FALSE, 0);

  raedlabelbienvenue3 = gtk_label_new (_("Bienvenue dans votre Espace-Admin"));
  gtk_widget_show (raedlabelbienvenue3);
  gtk_fixed_put (GTK_FIXED (fixed35), raedlabelbienvenue3, 136, 8);
  gtk_widget_set_size_request (raedlabelbienvenue3, 320, 41);

  raedlabelrechercher = gtk_label_new (_("Supprimer"));
  gtk_widget_show (raedlabelrechercher);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (raednotebook10), gtk_notebook_get_nth_page (GTK_NOTEBOOK (raednotebook10), 3), raedlabelrechercher);

  MalekMhatliWCourseSportif = gtk_label_new (_("Cours Sportifs"));
  gtk_widget_show (MalekMhatliWCourseSportif);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (MalekMhatlinotebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (MalekMhatlinotebook1), 2), MalekMhatliWCourseSportif);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (MalekMhatlinotebook1), empty_notebook_page);

  MalekMhatliWEquipement = gtk_label_new (_("Equipements"));
  gtk_widget_show (MalekMhatliWEquipement);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (MalekMhatlinotebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (MalekMhatlinotebook1), 3), MalekMhatliWEquipement);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (MalekMhatlinotebook1), empty_notebook_page);

  MalekMhatliWCenters = gtk_label_new (_("Centres"));
  gtk_widget_show (MalekMhatliWCenters);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (MalekMhatlinotebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (MalekMhatlinotebook1), 4), MalekMhatliWCenters);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (MalekMhatlinotebook1), empty_notebook_page);

  MalekMhatliWEvents = gtk_label_new (_("Evenements"));
  gtk_widget_show (MalekMhatliWEvents);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (MalekMhatlinotebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (MalekMhatlinotebook1), 5), MalekMhatliWEvents);

  g_signal_connect ((gpointer) raedbuttonrecherche, "clicked",
                    G_CALLBACK (on_raedbuttonrecherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) raedspinbuttonday1, "value_changed",
                    G_CALLBACK (on_raedspinbuttonday1_value_changed),
                    NULL);
  g_signal_connect ((gpointer) raedspinbuttonmonth1, "value_changed",
                    G_CALLBACK (on_raedspinbuttonmonth1_value_changed),
                    NULL);
  g_signal_connect ((gpointer) raedspinbuttonyear1, "value_changed",
                    G_CALLBACK (on_raedspinbuttonyear1_value_changed),
                    NULL);
  g_signal_connect ((gpointer) raedradiobutton10, "toggled",
                    G_CALLBACK (on_raedradiobutton10_toggled),
                    NULL);
  g_signal_connect ((gpointer) raedradiobutton11, "toggled",
                    G_CALLBACK (on_raedradiobutton11_toggled),
                    NULL);
  g_signal_connect_after ((gpointer) raedbutton42, "clicked",
                          G_CALLBACK (on_raedbutton42_clicked),
                          NULL);
  g_signal_connect ((gpointer) raedbutton45, "clicked",
                    G_CALLBACK (on_raedbutton45_clicked),
                    NULL);
  g_signal_connect ((gpointer) raedbutton43, "clicked",
                    G_CALLBACK (on_raedbutton43_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MalekMhatliWAdmin, MalekMhatliWAdmin, "MalekMhatliWAdmin");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, MalekMhatlinotebook1, "MalekMhatlinotebook1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, MalekMhatliWMemebers, "MalekMhatliWMemebers");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, MalekMhatliWCoach, "MalekMhatliWCoach");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raednotebook10, "raednotebook10");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, fixed, "fixed");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedentryrecherche, "raedentryrecherche");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedwindowcourrecherche, "raedwindowcourrecherche");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedtreeviewrecherche, "raedtreeviewrecherche");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelbienvenue1, "raedlabelbienvenue1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedbuttonrecherche, "raedbuttonrecherche");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, image34, "image34");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, label237, "label237");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelrecherche, "raedlabelrecherche");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, fixed33, "fixed33");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedentryid1, "raedentryid1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedentrynom1, "raedentrynom1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedentrycentre1, "raedentrycentre1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedspinbuttonday1, "raedspinbuttonday1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedspinbuttonmonth1, "raedspinbuttonmonth1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedspinbuttonyear1, "raedspinbuttonyear1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabeldate1, "raedlabeldate1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelidantifiant, "raedlabelidantifiant");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelspecialit__1, "raedlabelspecialit__1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelcentre1, "raedlabelcentre1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabel321, "raedlabel321");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelnom1, "raedlabelnom1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedradiobutton10, "raedradiobutton10");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedradiobutton11, "raedradiobutton11");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedbutton42, "raedbutton42");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedalignmentajouter1, "raedalignmentajouter1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, image36, "image36");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, label252, "label252");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedcomboboxentryspecialit__1, "raedcomboboxentryspecialit__1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelajout, "raedlabelajout");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, fixed34, "fixed34");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedspinbuttonday2, "raedspinbuttonday2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedspinbuttonmonth2, "raedspinbuttonmonth2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedspinbuttonyear2, "raedspinbuttonyear2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedentrynom2, "raedentrynom2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedentryid2, "raedentryid2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedentrycour2, "raedentrycour2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabeldate2, "raedlabeldate2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelspecialit__2, "raedlabelspecialit__2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelcentre2, "raedlabelcentre2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelnom2, "raedlabelnom2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelid2, "raedlabelid2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedcomboboxentryspecialit__2, "raedcomboboxentryspecialit__2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedbutton45, "raedbutton45");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedalignmentmodifier2, "raedalignmentmodifier2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, image39, "image39");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, label258, "label258");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelbienvenue2, "raedlabelbienvenue2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelrmodifier, "raedlabelrmodifier");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, fixed35, "fixed35");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedentryid3, "raedentryid3");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelid3, "raedlabelid3");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedbutton43, "raedbutton43");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedalignmentsupprimer3, "raedalignmentsupprimer3");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, image37, "image37");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, label255, "label255");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelbienvenue3, "raedlabelbienvenue3");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, raedlabelrechercher, "raedlabelrechercher");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, MalekMhatliWCourseSportif, "MalekMhatliWCourseSportif");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, MalekMhatliWEquipement, "MalekMhatliWEquipement");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, MalekMhatliWCenters, "MalekMhatliWCenters");
  GLADE_HOOKUP_OBJECT (MalekMhatliWAdmin, MalekMhatliWEvents, "MalekMhatliWEvents");

  return MalekMhatliWAdmin;
}

GtkWidget*
create_MalekMhatliWEntraineur (void)
{
  GtkWidget *MalekMhatliWEntraineur;
  GtkWidget *notebook7;
  GtkWidget *fixed22;
  GtkWidget *MMTV5;
  GtkObject *MMsbJ4_adj;
  GtkWidget *MMsbJ4;
  GtkObject *MMsbMois4_adj;
  GtkWidget *MMsbMois4;
  GtkObject *MMsbAn4_adj;
  GtkWidget *MMsbAn4;
  GtkWidget *MalekMhatliLabelDateDeSeance;
  GtkWidget *MalekMhatlilabelHour1;
  GtkWidget *MMcomboxentH2;
  GtkWidget *MMbAjout6;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image16;
  GtkWidget *label141;
  GtkWidget *MMbRet1;
  GtkWidget *MalekMhatlialignmentD__connecter2;
  GtkWidget *hbox2;
  GtkWidget *MalekMhatliReturn;
  GtkWidget *MalekMhatlilabelD__connecter3;
  GtkWidget *label129;
  GtkWidget *fixed27;
  GtkWidget *_safa_riahi_entry_id_entraineur;
  GtkWidget *safa_riahi_entry_nom_complet;
  GtkWidget *button_s_inscrire_;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image24;
  GtkWidget *label185;
  GtkWidget *_safa_riahi_button_annuler;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image23;
  GtkWidget *label184;
  GtkWidget *_safa_riahi_label_mes_informations;
  GtkWidget *_safa_riahi_label_id_entraineur;
  GtkWidget *_safa_riahi_label_nom_complet_entraineur;
  GtkWidget *__safa_riahi_label_Centres_Sportifs_;
  GtkWidget *_safa_riahi_scrolledwindow_entraineur_;
  GtkWidget *_safa_riahi_treeview_entraineur;
  GtkWidget *_safa_riahi_label_entraineur;
  GtkWidget *fixed38;
  GtkWidget *label283;
  GtkWidget *label284;
  GtkWidget *fdentryidins;
  GtkWidget *fdentryeveins;
  GtkWidget *fdtreeviewdispo;
  GtkWidget *label286;
  GtkWidget *label285;
  GtkWidget *label312;
  GtkWidget *radiobutton8;
  GSList *radiobutton8_group = NULL;
  GtkWidget *radiobutton9;
  GtkWidget *label282;

  MalekMhatliWEntraineur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MalekMhatliWEntraineur), _("Espace-Entraineur"));

  notebook7 = gtk_notebook_new ();
  gtk_widget_show (notebook7);
  gtk_container_add (GTK_CONTAINER (MalekMhatliWEntraineur), notebook7);

  fixed22 = gtk_fixed_new ();
  gtk_widget_show (fixed22);
  gtk_container_add (GTK_CONTAINER (notebook7), fixed22);

  MMTV5 = gtk_tree_view_new ();
  gtk_widget_show (MMTV5);
  gtk_fixed_put (GTK_FIXED (fixed22), MMTV5, 24, 24);
  gtk_widget_set_size_request (MMTV5, 472, 368);

  MMsbJ4_adj = gtk_adjustment_new (10, 0, 31, 1, 10, 10);
  MMsbJ4 = gtk_spin_button_new (GTK_ADJUSTMENT (MMsbJ4_adj), 1, 0);
  gtk_widget_show (MMsbJ4);
  gtk_fixed_put (GTK_FIXED (fixed22), MMsbJ4, 504, 120);
  gtk_widget_set_size_request (MMsbJ4, 60, 27);

  MMsbMois4_adj = gtk_adjustment_new (11, 0, 12, 1, 10, 10);
  MMsbMois4 = gtk_spin_button_new (GTK_ADJUSTMENT (MMsbMois4_adj), 1, 0);
  gtk_widget_show (MMsbMois4);
  gtk_fixed_put (GTK_FIXED (fixed22), MMsbMois4, 584, 120);
  gtk_widget_set_size_request (MMsbMois4, 60, 27);

  MMsbAn4_adj = gtk_adjustment_new (2025, 0, 2030, 1, 10, 10);
  MMsbAn4 = gtk_spin_button_new (GTK_ADJUSTMENT (MMsbAn4_adj), 1, 0);
  gtk_widget_show (MMsbAn4);
  gtk_fixed_put (GTK_FIXED (fixed22), MMsbAn4, 664, 120);
  gtk_widget_set_size_request (MMsbAn4, 60, 27);

  MalekMhatliLabelDateDeSeance = gtk_label_new (_("Date de S\303\251ance :"));
  gtk_widget_show (MalekMhatliLabelDateDeSeance);
  gtk_fixed_put (GTK_FIXED (fixed22), MalekMhatliLabelDateDeSeance, 520, 40);
  gtk_widget_set_size_request (MalekMhatliLabelDateDeSeance, 192, 48);

  MalekMhatlilabelHour1 = gtk_label_new (_("Heure de S\303\251ance :"));
  gtk_widget_show (MalekMhatlilabelHour1);
  gtk_fixed_put (GTK_FIXED (fixed22), MalekMhatlilabelHour1, 520, 168);
  gtk_widget_set_size_request (MalekMhatlilabelHour1, 192, 56);

  MMcomboxentH2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (MMcomboxentH2);
  gtk_fixed_put (GTK_FIXED (fixed22), MMcomboxentH2, 528, 240);
  gtk_widget_set_size_request (MMcomboxentH2, 189, 29);

  MMbAjout6 = gtk_button_new ();
  gtk_widget_show (MMbAjout6);
  gtk_fixed_put (GTK_FIXED (fixed22), MMbAjout6, 536, 328);
  gtk_widget_set_size_request (MMbAjout6, 160, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (MMbAjout6), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image16 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox8), image16, FALSE, FALSE, 0);

  label141 = gtk_label_new_with_mnemonic (_("S'inscrire"));
  gtk_widget_show (label141);
  gtk_box_pack_start (GTK_BOX (hbox8), label141, FALSE, FALSE, 0);

  MMbRet1 = gtk_button_new ();
  gtk_widget_show (MMbRet1);
  gtk_fixed_put (GTK_FIXED (fixed22), MMbRet1, 312, 416);
  gtk_widget_set_size_request (MMbRet1, 160, 48);

  MalekMhatlialignmentD__connecter2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (MalekMhatlialignmentD__connecter2);
  gtk_container_add (GTK_CONTAINER (MMbRet1), MalekMhatlialignmentD__connecter2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (MalekMhatlialignmentD__connecter2), hbox2);

  MalekMhatliReturn = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (MalekMhatliReturn);
  gtk_box_pack_start (GTK_BOX (hbox2), MalekMhatliReturn, FALSE, FALSE, 0);

  MalekMhatlilabelD__connecter3 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (MalekMhatlilabelD__connecter3);
  gtk_box_pack_start (GTK_BOX (hbox2), MalekMhatlilabelD__connecter3, FALSE, FALSE, 0);

  label129 = gtk_label_new (_("S'inscrire \303\240 un cours"));
  gtk_widget_show (label129);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook7), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook7), 0), label129);

  fixed27 = gtk_fixed_new ();
  gtk_widget_show (fixed27);
  gtk_container_add (GTK_CONTAINER (notebook7), fixed27);

  _safa_riahi_entry_id_entraineur = gtk_entry_new ();
  gtk_widget_show (_safa_riahi_entry_id_entraineur);
  gtk_fixed_put (GTK_FIXED (fixed27), _safa_riahi_entry_id_entraineur, 184, 72);
  gtk_widget_set_size_request (_safa_riahi_entry_id_entraineur, 208, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (_safa_riahi_entry_id_entraineur), 8226);

  safa_riahi_entry_nom_complet = gtk_entry_new ();
  gtk_widget_show (safa_riahi_entry_nom_complet);
  gtk_fixed_put (GTK_FIXED (fixed27), safa_riahi_entry_nom_complet, 184, 128);
  gtk_widget_set_size_request (safa_riahi_entry_nom_complet, 208, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (safa_riahi_entry_nom_complet), 8226);

  button_s_inscrire_ = gtk_button_new ();
  gtk_widget_show (button_s_inscrire_);
  gtk_fixed_put (GTK_FIXED (fixed27), button_s_inscrire_, 432, 464);
  gtk_widget_set_size_request (button_s_inscrire_, 154, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_s_inscrire_), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image24 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox16), image24, FALSE, FALSE, 0);

  label185 = gtk_label_new_with_mnemonic (_("s'inscrire"));
  gtk_widget_show (label185);
  gtk_box_pack_start (GTK_BOX (hbox16), label185, FALSE, FALSE, 0);

  _safa_riahi_button_annuler = gtk_button_new ();
  gtk_widget_show (_safa_riahi_button_annuler);
  gtk_fixed_put (GTK_FIXED (fixed27), _safa_riahi_button_annuler, 88, 464);
  gtk_widget_set_size_request (_safa_riahi_button_annuler, 152, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (_safa_riahi_button_annuler), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image23 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox15), image23, FALSE, FALSE, 0);

  label184 = gtk_label_new_with_mnemonic (_("cancel"));
  gtk_widget_show (label184);
  gtk_box_pack_start (GTK_BOX (hbox15), label184, FALSE, FALSE, 0);

  _safa_riahi_label_mes_informations = gtk_label_new (_("Mes  informations "));
  gtk_widget_show (_safa_riahi_label_mes_informations);
  gtk_fixed_put (GTK_FIXED (fixed27), _safa_riahi_label_mes_informations, 128, 8);
  gtk_widget_set_size_request (_safa_riahi_label_mes_informations, 337, 41);

  _safa_riahi_label_id_entraineur = gtk_label_new (_("ID Entraineur :"));
  gtk_widget_show (_safa_riahi_label_id_entraineur);
  gtk_fixed_put (GTK_FIXED (fixed27), _safa_riahi_label_id_entraineur, 24, 80);
  gtk_widget_set_size_request (_safa_riahi_label_id_entraineur, 129, 25);

  _safa_riahi_label_nom_complet_entraineur = gtk_label_new (_("Nom Complet :"));
  gtk_widget_show (_safa_riahi_label_nom_complet_entraineur);
  gtk_fixed_put (GTK_FIXED (fixed27), _safa_riahi_label_nom_complet_entraineur, 8, 128);
  gtk_widget_set_size_request (_safa_riahi_label_nom_complet_entraineur, 168, 32);

  __safa_riahi_label_Centres_Sportifs_ = gtk_label_new (_("Centres Sportifs Disponibles :"));
  gtk_widget_show (__safa_riahi_label_Centres_Sportifs_);
  gtk_fixed_put (GTK_FIXED (fixed27), __safa_riahi_label_Centres_Sportifs_, 0, 184);
  gtk_widget_set_size_request (__safa_riahi_label_Centres_Sportifs_, 264, 33);

  _safa_riahi_scrolledwindow_entraineur_ = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (_safa_riahi_scrolledwindow_entraineur_);
  gtk_fixed_put (GTK_FIXED (fixed27), _safa_riahi_scrolledwindow_entraineur_, 32, 240);
  gtk_widget_set_size_request (_safa_riahi_scrolledwindow_entraineur_, 600, 210);

  _safa_riahi_treeview_entraineur = gtk_tree_view_new ();
  gtk_widget_show (_safa_riahi_treeview_entraineur);
  gtk_container_add (GTK_CONTAINER (_safa_riahi_scrolledwindow_entraineur_), _safa_riahi_treeview_entraineur);

  _safa_riahi_label_entraineur = gtk_label_new (_("S'inscrire \303\240 un centre"));
  gtk_widget_show (_safa_riahi_label_entraineur);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook7), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook7), 1), _safa_riahi_label_entraineur);

  fixed38 = gtk_fixed_new ();
  gtk_widget_show (fixed38);
  gtk_container_add (GTK_CONTAINER (notebook7), fixed38);

  label283 = gtk_label_new (_("Mes  informations "));
  gtk_widget_show (label283);
  gtk_fixed_put (GTK_FIXED (fixed38), label283, 128, 8);
  gtk_widget_set_size_request (label283, 337, 41);

  label284 = gtk_label_new (_("ID Entraineur :"));
  gtk_widget_show (label284);
  gtk_fixed_put (GTK_FIXED (fixed38), label284, 64, 72);
  gtk_widget_set_size_request (label284, 129, 25);

  fdentryidins = gtk_entry_new ();
  gtk_widget_show (fdentryidins);
  gtk_fixed_put (GTK_FIXED (fixed38), fdentryidins, 224, 72);
  gtk_widget_set_size_request (fdentryidins, 208, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (fdentryidins), 8226);

  fdentryeveins = gtk_entry_new ();
  gtk_widget_show (fdentryeveins);
  gtk_fixed_put (GTK_FIXED (fixed38), fdentryeveins, 224, 136);
  gtk_widget_set_size_request (fdentryeveins, 208, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (fdentryeveins), 8226);

  fdtreeviewdispo = gtk_tree_view_new ();
  gtk_widget_show (fdtreeviewdispo);
  gtk_fixed_put (GTK_FIXED (fixed38), fdtreeviewdispo, 64, 248);
  gtk_widget_set_size_request (fdtreeviewdispo, 0, 0);

  label286 = gtk_label_new (_("Centres Sportifs Disponibles :"));
  gtk_widget_show (label286);
  gtk_fixed_put (GTK_FIXED (fixed38), label286, 0, 208);
  gtk_widget_set_size_request (label286, 264, 33);

  label285 = gtk_label_new (_("evenement  :"));
  gtk_widget_show (label285);
  gtk_fixed_put (GTK_FIXED (fixed38), label285, 48, 136);
  gtk_widget_set_size_request (label285, 168, 32);

  label312 = gtk_label_new (_("tu as tous les equipements necessaires :"));
  gtk_widget_show (label312);
  gtk_fixed_put (GTK_FIXED (fixed38), label312, 392, 272);
  gtk_widget_set_size_request (label312, 280, 16);

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("oui"));
  gtk_widget_show (radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed38), radiobutton8, 400, 312);
  gtk_widget_set_size_request (radiobutton8, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton8_group);
  radiobutton8_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  radiobutton9 = gtk_radio_button_new_with_mnemonic (NULL, _("non"));
  gtk_widget_show (radiobutton9);
  gtk_fixed_put (GTK_FIXED (fixed38), radiobutton9, 496, 312);
  gtk_widget_set_size_request (radiobutton9, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton9), radiobutton8_group);
  radiobutton8_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton9));

  label282 = gtk_label_new (_("s'inscrire a un evenements"));
  gtk_widget_show (label282);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook7), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook7), 2), label282);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MalekMhatliWEntraineur, MalekMhatliWEntraineur, "MalekMhatliWEntraineur");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, notebook7, "notebook7");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, fixed22, "fixed22");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, MMTV5, "MMTV5");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, MMsbJ4, "MMsbJ4");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, MMsbMois4, "MMsbMois4");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, MMsbAn4, "MMsbAn4");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, MalekMhatliLabelDateDeSeance, "MalekMhatliLabelDateDeSeance");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, MalekMhatlilabelHour1, "MalekMhatlilabelHour1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, MMcomboxentH2, "MMcomboxentH2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, MMbAjout6, "MMbAjout6");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, image16, "image16");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, label141, "label141");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, MMbRet1, "MMbRet1");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, MalekMhatlialignmentD__connecter2, "MalekMhatlialignmentD__connecter2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, MalekMhatliReturn, "MalekMhatliReturn");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, MalekMhatlilabelD__connecter3, "MalekMhatlilabelD__connecter3");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, label129, "label129");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, fixed27, "fixed27");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, _safa_riahi_entry_id_entraineur, "_safa_riahi_entry_id_entraineur");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, safa_riahi_entry_nom_complet, "safa_riahi_entry_nom_complet");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, button_s_inscrire_, "button_s_inscrire_");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, image24, "image24");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, label185, "label185");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, _safa_riahi_button_annuler, "_safa_riahi_button_annuler");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, image23, "image23");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, label184, "label184");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, _safa_riahi_label_mes_informations, "_safa_riahi_label_mes_informations");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, _safa_riahi_label_id_entraineur, "_safa_riahi_label_id_entraineur");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, _safa_riahi_label_nom_complet_entraineur, "_safa_riahi_label_nom_complet_entraineur");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, __safa_riahi_label_Centres_Sportifs_, "__safa_riahi_label_Centres_Sportifs_");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, _safa_riahi_scrolledwindow_entraineur_, "_safa_riahi_scrolledwindow_entraineur_");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, _safa_riahi_treeview_entraineur, "_safa_riahi_treeview_entraineur");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, _safa_riahi_label_entraineur, "_safa_riahi_label_entraineur");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, fixed38, "fixed38");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, label283, "label283");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, label284, "label284");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, fdentryidins, "fdentryidins");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, fdentryeveins, "fdentryeveins");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, fdtreeviewdispo, "fdtreeviewdispo");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, label286, "label286");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, label285, "label285");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, label312, "label312");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (MalekMhatliWEntraineur, label282, "label282");

  return MalekMhatliWEntraineur;
}

GtkWidget*
create_MalekMhatliWModifier5 (void)
{
  GtkWidget *MalekMhatliWModifier5;
  GtkWidget *fixed28;
  GtkWidget *entry68;
  GtkWidget *textview36;
  GtkWidget *textview37;
  GtkWidget *textview38;
  GtkWidget *textview39;
  GtkWidget *textview40;
  GtkWidget *textview41;
  GtkWidget *textview42;
  GtkWidget *textview43;
  GtkWidget *entry69;
  GtkWidget *entry70;
  GtkObject *spinbutton28_adj;
  GtkWidget *spinbutton28;
  GtkObject *spinbutton29_adj;
  GtkWidget *spinbutton29;
  GtkObject *spinbutton30_adj;
  GtkWidget *spinbutton30;
  GtkWidget *entry71;
  GtkWidget *entry72;
  GtkWidget *entry73;
  GtkWidget *entry74;
  GtkWidget *entry75;
  GtkWidget *label195;
  GtkWidget *label196;
  GtkWidget *label197;
  GtkWidget *label198;
  GtkWidget *label199;
  GtkWidget *label200;
  GtkWidget *label201;
  GtkWidget *radiobutton6;
  GSList *radiobutton6_group = NULL;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *label202;
  GtkWidget *button32;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image27;
  GtkWidget *label203;
  GtkWidget *label204;
  GtkWidget *label205;
  GtkWidget *button33;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image28;
  GtkWidget *label206;
  GtkWidget *label207;
  GtkWidget *textview44;

  MalekMhatliWModifier5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MalekMhatliWModifier5), _("Modifier"));

  fixed28 = gtk_fixed_new ();
  gtk_widget_show (fixed28);
  gtk_container_add (GTK_CONTAINER (MalekMhatliWModifier5), fixed28);

  entry68 = gtk_entry_new ();
  gtk_widget_show (entry68);
  gtk_fixed_put (GTK_FIXED (fixed28), entry68, 176, 56);
  gtk_widget_set_size_request (entry68, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry68), 8226);

  textview36 = gtk_text_view_new ();
  gtk_widget_show (textview36);
  gtk_fixed_put (GTK_FIXED (fixed28), textview36, 176, 104);
  gtk_widget_set_size_request (textview36, 168, 24);

  textview37 = gtk_text_view_new ();
  gtk_widget_show (textview37);
  gtk_fixed_put (GTK_FIXED (fixed28), textview37, 176, 144);
  gtk_widget_set_size_request (textview37, 168, 24);

  textview38 = gtk_text_view_new ();
  gtk_widget_show (textview38);
  gtk_fixed_put (GTK_FIXED (fixed28), textview38, 176, 184);
  gtk_widget_set_size_request (textview38, 168, 24);

  textview39 = gtk_text_view_new ();
  gtk_widget_show (textview39);
  gtk_fixed_put (GTK_FIXED (fixed28), textview39, 176, 272);
  gtk_widget_set_size_request (textview39, 168, 24);

  textview40 = gtk_text_view_new ();
  gtk_widget_show (textview40);
  gtk_fixed_put (GTK_FIXED (fixed28), textview40, 176, 320);
  gtk_widget_set_size_request (textview40, 168, 24);

  textview41 = gtk_text_view_new ();
  gtk_widget_show (textview41);
  gtk_fixed_put (GTK_FIXED (fixed28), textview41, 176, 368);
  gtk_widget_set_size_request (textview41, 168, 24);

  textview42 = gtk_text_view_new ();
  gtk_widget_show (textview42);
  gtk_fixed_put (GTK_FIXED (fixed28), textview42, 176, 408);
  gtk_widget_set_size_request (textview42, 168, 24);

  textview43 = gtk_text_view_new ();
  gtk_widget_show (textview43);
  gtk_fixed_put (GTK_FIXED (fixed28), textview43, 176, 448);
  gtk_widget_set_size_request (textview43, 168, 24);

  entry69 = gtk_entry_new ();
  gtk_widget_show (entry69);
  gtk_fixed_put (GTK_FIXED (fixed28), entry69, 392, 104);
  gtk_widget_set_size_request (entry69, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry69), 8226);

  entry70 = gtk_entry_new ();
  gtk_widget_show (entry70);
  gtk_fixed_put (GTK_FIXED (fixed28), entry70, 392, 144);
  gtk_widget_set_size_request (entry70, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry70), 8226);

  spinbutton28_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  spinbutton28 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton28_adj), 1, 0);
  gtk_widget_show (spinbutton28);
  gtk_fixed_put (GTK_FIXED (fixed28), spinbutton28, 376, 224);
  gtk_widget_set_size_request (spinbutton28, 60, 27);

  spinbutton29_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  spinbutton29 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton29_adj), 1, 0);
  gtk_widget_show (spinbutton29);
  gtk_fixed_put (GTK_FIXED (fixed28), spinbutton29, 448, 224);
  gtk_widget_set_size_request (spinbutton29, 60, 27);

  spinbutton30_adj = gtk_adjustment_new (1, 0, 2026, 1, 10, 10);
  spinbutton30 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton30_adj), 1, 0);
  gtk_widget_show (spinbutton30);
  gtk_fixed_put (GTK_FIXED (fixed28), spinbutton30, 520, 224);
  gtk_widget_set_size_request (spinbutton30, 60, 27);

  entry71 = gtk_entry_new ();
  gtk_widget_show (entry71);
  gtk_fixed_put (GTK_FIXED (fixed28), entry71, 392, 272);
  gtk_widget_set_size_request (entry71, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry71), 8226);

  entry72 = gtk_entry_new ();
  gtk_widget_show (entry72);
  gtk_fixed_put (GTK_FIXED (fixed28), entry72, 392, 320);
  gtk_widget_set_size_request (entry72, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry72), 8226);

  entry73 = gtk_entry_new ();
  gtk_widget_show (entry73);
  gtk_fixed_put (GTK_FIXED (fixed28), entry73, 392, 368);
  gtk_widget_set_size_request (entry73, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry73), 8226);

  entry74 = gtk_entry_new ();
  gtk_widget_show (entry74);
  gtk_fixed_put (GTK_FIXED (fixed28), entry74, 392, 408);
  gtk_widget_set_size_request (entry74, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry74), 8226);

  entry75 = gtk_entry_new ();
  gtk_widget_show (entry75);
  gtk_fixed_put (GTK_FIXED (fixed28), entry75, 392, 448);
  gtk_widget_set_size_request (entry75, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry75), 8226);

  label195 = gtk_label_new (_("Mot de Passe :"));
  gtk_widget_show (label195);
  gtk_fixed_put (GTK_FIXED (fixed28), label195, 32, 440);
  gtk_widget_set_size_request (label195, 136, 32);

  label196 = gtk_label_new (_("Sp\303\251cialit\303\251 :"));
  gtk_widget_show (label196);
  gtk_fixed_put (GTK_FIXED (fixed28), label196, 24, 360);
  gtk_widget_set_size_request (label196, 120, 32);

  label197 = gtk_label_new (_("T\303\251l\303\251phone :"));
  gtk_widget_show (label197);
  gtk_fixed_put (GTK_FIXED (fixed28), label197, 24, 312);
  gtk_widget_set_size_request (label197, 120, 32);

  label198 = gtk_label_new (_("Adresse email :"));
  gtk_widget_show (label198);
  gtk_fixed_put (GTK_FIXED (fixed28), label198, 32, 272);
  gtk_widget_set_size_request (label198, 128, 32);

  label199 = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label199);
  gtk_fixed_put (GTK_FIXED (fixed28), label199, 32, 184);
  gtk_widget_set_size_request (label199, 80, 24);

  label200 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label200);
  gtk_fixed_put (GTK_FIXED (fixed28), label200, 24, 144);
  gtk_widget_set_size_request (label200, 96, 24);

  label201 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label201);
  gtk_fixed_put (GTK_FIXED (fixed28), label201, 24, 96);
  gtk_widget_set_size_request (label201, 88, 32);

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed28), radiobutton6, 376, 184);
  gtk_widget_set_size_request (radiobutton6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton6_group);
  radiobutton6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed28), radiobutton7, 512, 184);
  gtk_widget_set_size_request (radiobutton7, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  label202 = gtk_label_new (_("Centre inscrit(e) \303\240 :"));
  gtk_widget_show (label202);
  gtk_fixed_put (GTK_FIXED (fixed28), label202, 24, 400);
  gtk_widget_set_size_request (label202, 168, 32);

  button32 = gtk_button_new ();
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed28), button32, 560, 48);
  gtk_widget_set_size_request (button32, 184, 48);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button32), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image27 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox19), image27, FALSE, FALSE, 0);

  label203 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label203);
  gtk_box_pack_start (GTK_BOX (hbox19), label203, FALSE, FALSE, 0);

  label204 = gtk_label_new (_("Bienvenue dans votre Espace-Admin"));
  gtk_widget_show (label204);
  gtk_fixed_put (GTK_FIXED (fixed28), label204, 216, 8);
  gtk_widget_set_size_request (label204, 320, 41);

  label205 = gtk_label_new (_("ID Entraineur :"));
  gtk_widget_show (label205);
  gtk_fixed_put (GTK_FIXED (fixed28), label205, 16, 64);
  gtk_widget_set_size_request (label205, 136, 24);

  button33 = gtk_button_new ();
  gtk_widget_show (button33);
  gtk_fixed_put (GTK_FIXED (fixed28), button33, 368, 48);
  gtk_widget_set_size_request (button33, 184, 48);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button33), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image28 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox20), image28, FALSE, FALSE, 0);

  label206 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label206);
  gtk_box_pack_start (GTK_BOX (hbox20), label206, FALSE, FALSE, 0);

  label207 = gtk_label_new (_("Date de Naissance :"));
  gtk_widget_show (label207);
  gtk_fixed_put (GTK_FIXED (fixed28), label207, 32, 224);
  gtk_widget_set_size_request (label207, 144, 32);

  textview44 = gtk_text_view_new ();
  gtk_widget_show (textview44);
  gtk_fixed_put (GTK_FIXED (fixed28), textview44, 176, 232);
  gtk_widget_set_size_request (textview44, 168, 24);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MalekMhatliWModifier5, MalekMhatliWModifier5, "MalekMhatliWModifier5");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, fixed28, "fixed28");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, entry68, "entry68");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, textview36, "textview36");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, textview37, "textview37");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, textview38, "textview38");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, textview39, "textview39");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, textview40, "textview40");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, textview41, "textview41");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, textview42, "textview42");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, textview43, "textview43");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, entry69, "entry69");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, entry70, "entry70");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, spinbutton28, "spinbutton28");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, spinbutton29, "spinbutton29");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, spinbutton30, "spinbutton30");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, entry71, "entry71");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, entry72, "entry72");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, entry73, "entry73");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, entry74, "entry74");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, entry75, "entry75");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, label195, "label195");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, label196, "label196");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, label197, "label197");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, label198, "label198");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, label199, "label199");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, label200, "label200");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, label201, "label201");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, label202, "label202");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, button32, "button32");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, image27, "image27");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, label203, "label203");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, label204, "label204");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, label205, "label205");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, button33, "button33");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, image28, "image28");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, label206, "label206");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, label207, "label207");
  GLADE_HOOKUP_OBJECT (MalekMhatliWModifier5, textview44, "textview44");

  return MalekMhatliWModifier5;
}

GtkWidget*
create_MalekMhatliWindowSupp5 (void)
{
  GtkWidget *MalekMhatliWindowSupp5;
  GtkWidget *fixed29;
  GtkWidget *entry76;
  GtkWidget *textview45;
  GtkWidget *label208;
  GtkWidget *button34;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image29;
  GtkWidget *label209;
  GtkWidget *label210;

  MalekMhatliWindowSupp5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MalekMhatliWindowSupp5), _("Supprimer"));

  fixed29 = gtk_fixed_new ();
  gtk_widget_show (fixed29);
  gtk_container_add (GTK_CONTAINER (MalekMhatliWindowSupp5), fixed29);

  entry76 = gtk_entry_new ();
  gtk_widget_show (entry76);
  gtk_fixed_put (GTK_FIXED (fixed29), entry76, 264, 168);
  gtk_widget_set_size_request (entry76, 200, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry76), 8226);

  textview45 = gtk_text_view_new ();
  gtk_widget_show (textview45);
  gtk_fixed_put (GTK_FIXED (fixed29), textview45, 520, 168);
  gtk_widget_set_size_request (textview45, 192, 48);

  label208 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label208);
  gtk_fixed_put (GTK_FIXED (fixed29), label208, 16, 168);
  gtk_widget_set_size_request (label208, 232, 56);

  button34 = gtk_button_new ();
  gtk_widget_show (button34);
  gtk_fixed_put (GTK_FIXED (fixed29), button34, 248, 328);
  gtk_widget_set_size_request (button34, 232, 48);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button34), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image29 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox21), image29, FALSE, FALSE, 0);

  label209 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label209);
  gtk_box_pack_start (GTK_BOX (hbox21), label209, FALSE, FALSE, 0);

  label210 = gtk_label_new (_("Bienvenue dans votre Espace-Admin"));
  gtk_widget_show (label210);
  gtk_fixed_put (GTK_FIXED (fixed29), label210, 216, 8);
  gtk_widget_set_size_request (label210, 320, 41);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MalekMhatliWindowSupp5, MalekMhatliWindowSupp5, "MalekMhatliWindowSupp5");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowSupp5, fixed29, "fixed29");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowSupp5, entry76, "entry76");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowSupp5, textview45, "textview45");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowSupp5, label208, "label208");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowSupp5, button34, "button34");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowSupp5, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowSupp5, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowSupp5, image29, "image29");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowSupp5, label209, "label209");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowSupp5, label210, "label210");

  return MalekMhatliWindowSupp5;
}

GtkWidget*
create_MalekMhatliWindowAjout5 (void)
{
  GtkWidget *MalekMhatliWindowAjout5;
  GtkWidget *fixed30;
  GtkWidget *entry77;
  GtkWidget *entry78;
  GtkWidget *entry79;
  GtkObject *spinbutton31_adj;
  GtkWidget *spinbutton31;
  GtkObject *spinbutton32_adj;
  GtkWidget *spinbutton32;
  GtkObject *spinbutton33_adj;
  GtkWidget *spinbutton33;
  GtkWidget *entry80;
  GtkWidget *entry81;
  GtkWidget *entry82;
  GtkWidget *label211;
  GtkWidget *label212;
  GtkWidget *label213;
  GtkWidget *label214;
  GtkWidget *comboboxentry9;
  GtkWidget *label215;
  GtkWidget *label216;
  GtkWidget *label217;
  GtkWidget *checkbutton3;
  GtkWidget *label218;
  GtkWidget *checkbutton4;
  GtkWidget *label219;
  GtkWidget *label220;
  GtkWidget *button35;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image30;
  GtkWidget *label221;

  MalekMhatliWindowAjout5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MalekMhatliWindowAjout5), _("Ajouter"));

  fixed30 = gtk_fixed_new ();
  gtk_widget_show (fixed30);
  gtk_container_add (GTK_CONTAINER (MalekMhatliWindowAjout5), fixed30);

  entry77 = gtk_entry_new ();
  gtk_widget_show (entry77);
  gtk_fixed_put (GTK_FIXED (fixed30), entry77, 320, 72);
  gtk_widget_set_size_request (entry77, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry77), 8226);

  entry78 = gtk_entry_new ();
  gtk_widget_show (entry78);
  gtk_fixed_put (GTK_FIXED (fixed30), entry78, 320, 120);
  gtk_widget_set_size_request (entry78, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry78), 8226);

  entry79 = gtk_entry_new ();
  gtk_widget_show (entry79);
  gtk_fixed_put (GTK_FIXED (fixed30), entry79, 320, 168);
  gtk_widget_set_size_request (entry79, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry79), 8226);

  spinbutton31_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  spinbutton31 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton31_adj), 1, 0);
  gtk_widget_show (spinbutton31);
  gtk_fixed_put (GTK_FIXED (fixed30), spinbutton31, 296, 264);
  gtk_widget_set_size_request (spinbutton31, 60, 27);

  spinbutton32_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  spinbutton32 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton32_adj), 1, 0);
  gtk_widget_show (spinbutton32);
  gtk_fixed_put (GTK_FIXED (fixed30), spinbutton32, 400, 264);
  gtk_widget_set_size_request (spinbutton32, 60, 27);

  spinbutton33_adj = gtk_adjustment_new (1, 0, 2026, 1, 10, 10);
  spinbutton33 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton33_adj), 1, 0);
  gtk_widget_show (spinbutton33);
  gtk_fixed_put (GTK_FIXED (fixed30), spinbutton33, 504, 264);
  gtk_widget_set_size_request (spinbutton33, 60, 27);

  entry80 = gtk_entry_new ();
  gtk_widget_show (entry80);
  gtk_fixed_put (GTK_FIXED (fixed30), entry80, 320, 312);
  gtk_widget_set_size_request (entry80, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry80), 8226);

  entry81 = gtk_entry_new ();
  gtk_widget_show (entry81);
  gtk_fixed_put (GTK_FIXED (fixed30), entry81, 320, 352);
  gtk_widget_set_size_request (entry81, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry81), 8226);

  entry82 = gtk_entry_new ();
  gtk_widget_show (entry82);
  gtk_fixed_put (GTK_FIXED (fixed30), entry82, 320, 440);
  gtk_widget_set_size_request (entry82, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry82), 8226);

  label211 = gtk_label_new (_("Adresse email :"));
  gtk_widget_show (label211);
  gtk_fixed_put (GTK_FIXED (fixed30), label211, 120, 304);
  gtk_widget_set_size_request (label211, 128, 32);

  label212 = gtk_label_new (_("T\303\251l\303\251phone :"));
  gtk_widget_show (label212);
  gtk_fixed_put (GTK_FIXED (fixed30), label212, 120, 344);
  gtk_widget_set_size_request (label212, 120, 32);

  label213 = gtk_label_new (_("Sp\303\251cialit\303\251 :"));
  gtk_widget_show (label213);
  gtk_fixed_put (GTK_FIXED (fixed30), label213, 120, 392);
  gtk_widget_set_size_request (label213, 120, 32);

  label214 = gtk_label_new (_("Centre inscrit(e) \303\240 :"));
  gtk_widget_show (label214);
  gtk_fixed_put (GTK_FIXED (fixed30), label214, 112, 440);
  gtk_widget_set_size_request (label214, 168, 24);

  comboboxentry9 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry9);
  gtk_fixed_put (GTK_FIXED (fixed30), comboboxentry9, 320, 392);
  gtk_widget_set_size_request (comboboxentry9, 157, 32);

  label215 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label215);
  gtk_fixed_put (GTK_FIXED (fixed30), label215, 112, 72);
  gtk_widget_set_size_request (label215, 136, 24);

  label216 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label216);
  gtk_fixed_put (GTK_FIXED (fixed30), label216, 136, 120);
  gtk_widget_set_size_request (label216, 88, 32);

  label217 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label217);
  gtk_fixed_put (GTK_FIXED (fixed30), label217, 128, 168);
  gtk_widget_set_size_request (label217, 96, 24);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("Femme :"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed30), checkbutton3, 464, 216);
  gtk_widget_set_size_request (checkbutton3, 118, 24);

  label218 = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label218);
  gtk_fixed_put (GTK_FIXED (fixed30), label218, 120, 208);
  gtk_widget_set_size_request (label218, 128, 32);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("Homme"));
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed30), checkbutton4, 304, 216);
  gtk_widget_set_size_request (checkbutton4, 118, 24);

  label219 = gtk_label_new (_("Date de Naissance :"));
  gtk_widget_show (label219);
  gtk_fixed_put (GTK_FIXED (fixed30), label219, 120, 264);
  gtk_widget_set_size_request (label219, 144, 32);

  label220 = gtk_label_new (_("Bienvenue dans votre Espace-Admin"));
  gtk_widget_show (label220);
  gtk_fixed_put (GTK_FIXED (fixed30), label220, 216, 8);
  gtk_widget_set_size_request (label220, 320, 41);

  button35 = gtk_button_new ();
  gtk_widget_show (button35);
  gtk_fixed_put (GTK_FIXED (fixed30), button35, 536, 56);
  gtk_widget_set_size_request (button35, 184, 48);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button35), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image30 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox22), image30, FALSE, FALSE, 0);

  label221 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label221);
  gtk_box_pack_start (GTK_BOX (hbox22), label221, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MalekMhatliWindowAjout5, MalekMhatliWindowAjout5, "MalekMhatliWindowAjout5");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, fixed30, "fixed30");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, entry77, "entry77");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, entry78, "entry78");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, entry79, "entry79");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, spinbutton31, "spinbutton31");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, spinbutton32, "spinbutton32");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, spinbutton33, "spinbutton33");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, entry80, "entry80");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, entry81, "entry81");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, entry82, "entry82");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, label211, "label211");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, label212, "label212");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, label213, "label213");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, label214, "label214");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, comboboxentry9, "comboboxentry9");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, label215, "label215");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, label216, "label216");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, label217, "label217");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, label218, "label218");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, label219, "label219");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, label220, "label220");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, button35, "button35");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, image30, "image30");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowAjout5, label221, "label221");

  return MalekMhatliWindowAjout5;
}

GtkWidget*
create_MalekMhatliWindowCherche5 (void)
{
  GtkWidget *MalekMhatliWindowCherche5;
  GtkWidget *fixed31;
  GtkWidget *treeview8;
  GtkWidget *entry83;
  GtkWidget *button36;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image31;
  GtkWidget *label222;
  GtkWidget *button37;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image32;
  GtkWidget *label223;
  GtkWidget *label224;
  GtkWidget *label225;

  MalekMhatliWindowCherche5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MalekMhatliWindowCherche5), _("Rechercher"));

  fixed31 = gtk_fixed_new ();
  gtk_widget_show (fixed31);
  gtk_container_add (GTK_CONTAINER (MalekMhatliWindowCherche5), fixed31);

  treeview8 = gtk_tree_view_new ();
  gtk_widget_show (treeview8);
  gtk_fixed_put (GTK_FIXED (fixed31), treeview8, 96, 152);
  gtk_widget_set_size_request (treeview8, 552, 312);

  entry83 = gtk_entry_new ();
  gtk_widget_show (entry83);
  gtk_fixed_put (GTK_FIXED (fixed31), entry83, 40, 56);
  gtk_widget_set_size_request (entry83, 216, 56);
  gtk_entry_set_text (GTK_ENTRY (entry83), _("Chercher un Etraineur..."));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry83), 8226);

  button36 = gtk_button_new ();
  gtk_widget_show (button36);
  gtk_fixed_put (GTK_FIXED (fixed31), button36, 296, 56);
  gtk_widget_set_size_request (button36, 208, 56);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button36), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image31 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox23), image31, FALSE, FALSE, 0);

  label222 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label222);
  gtk_box_pack_start (GTK_BOX (hbox23), label222, FALSE, FALSE, 0);

  button37 = gtk_button_new ();
  gtk_widget_show (button37);
  gtk_fixed_put (GTK_FIXED (fixed31), button37, 528, 56);
  gtk_widget_set_size_request (button37, 184, 56);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button37), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image32 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox24), image32, FALSE, FALSE, 0);

  label223 = gtk_label_new (_("Refraichir"));
  gtk_widget_show (label223);
  gtk_box_pack_start (GTK_BOX (hbox24), label223, FALSE, FALSE, 0);

  label224 = gtk_label_new (_("Bienvenue dans votre Espace-Admin"));
  gtk_widget_show (label224);
  gtk_fixed_put (GTK_FIXED (fixed31), label224, 216, 8);
  gtk_widget_set_size_request (label224, 320, 41);

  label225 = gtk_label_new (_("Liste des Entraineurs :"));
  gtk_widget_show (label225);
  gtk_fixed_put (GTK_FIXED (fixed31), label225, 48, 120);
  gtk_widget_set_size_request (label225, 248, 24);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MalekMhatliWindowCherche5, MalekMhatliWindowCherche5, "MalekMhatliWindowCherche5");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, fixed31, "fixed31");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, treeview8, "treeview8");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, entry83, "entry83");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, button36, "button36");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, image31, "image31");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, label222, "label222");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, button37, "button37");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, image32, "image32");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, label223, "label223");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, label224, "label224");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindowCherche5, label225, "label225");

  return MalekMhatliWindowCherche5;
}

GtkWidget*
create_RaedWindowMembre (void)
{
  GtkWidget *RaedWindowMembre;
  GtkWidget *notebook11;
  GtkWidget *fixed36;
  GtkWidget *raedentrycentre5;
  GtkWidget *raedlabelbienvenue5;
  GtkWidget *raedlabelcoursdisponible5;
  GtkWidget *raedlabelcentre5;
  GtkWidget *raedlabelcour5;
  GtkWidget *raedlabelspecialit__5;
  GtkWidget *raedlabel322;
  GtkWidget *raedscrolledwindowcoursdisponible5;
  GtkWidget *raedtreeview12;
  GtkWidget *raedentrycour5;
  GtkWidget *raedcheckbutton6;
  GtkWidget *raedcheckbutton5;
  GtkWidget *raedcomboboxxentryspecialit__5;
  GtkWidget *raedbuttoninscrire5;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image41;
  GtkWidget *label275;
  GtkWidget *label268;
  GtkWidget *empty_notebook_page;
  GtkWidget *label269;
  GtkWidget *label270;

  RaedWindowMembre = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (RaedWindowMembre), _("Espace-Membre"));

  notebook11 = gtk_notebook_new ();
  gtk_widget_show (notebook11);
  gtk_container_add (GTK_CONTAINER (RaedWindowMembre), notebook11);

  fixed36 = gtk_fixed_new ();
  gtk_widget_show (fixed36);
  gtk_container_add (GTK_CONTAINER (notebook11), fixed36);

  raedentrycentre5 = gtk_entry_new ();
  gtk_widget_show (raedentrycentre5);
  gtk_fixed_put (GTK_FIXED (fixed36), raedentrycentre5, 376, 48);
  gtk_widget_set_size_request (raedentrycentre5, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (raedentrycentre5), 8226);

  raedlabelbienvenue5 = gtk_label_new (_("Bienvenue dans votre Espace-membre"));
  gtk_widget_show (raedlabelbienvenue5);
  gtk_fixed_put (GTK_FIXED (fixed36), raedlabelbienvenue5, 216, 8);
  gtk_widget_set_size_request (raedlabelbienvenue5, 320, 41);

  raedlabelcoursdisponible5 = gtk_label_new (_("Cours Sportifs Disponibles :"));
  gtk_widget_show (raedlabelcoursdisponible5);
  gtk_fixed_put (GTK_FIXED (fixed36), raedlabelcoursdisponible5, 0, 200);
  gtk_widget_set_size_request (raedlabelcoursdisponible5, 264, 33);

  raedlabelcentre5 = gtk_label_new (_("Centre :"));
  gtk_widget_show (raedlabelcentre5);
  gtk_fixed_put (GTK_FIXED (fixed36), raedlabelcentre5, 144, 48);
  gtk_widget_set_size_request (raedlabelcentre5, 120, 32);

  raedlabelcour5 = gtk_label_new (_("cour :"));
  gtk_widget_show (raedlabelcour5);
  gtk_fixed_put (GTK_FIXED (fixed36), raedlabelcour5, 168, 144);
  gtk_widget_set_size_request (raedlabelcour5, 57, 17);

  raedlabelspecialit__5 = gtk_label_new (_("Sp\303\251cialit\303\251 :"));
  gtk_widget_show (raedlabelspecialit__5);
  gtk_fixed_put (GTK_FIXED (fixed36), raedlabelspecialit__5, 152, 96);
  gtk_widget_set_size_request (raedlabelspecialit__5, 120, 32);

  raedlabel322 = gtk_label_new (_("niveau :"));
  gtk_widget_show (raedlabel322);
  gtk_fixed_put (GTK_FIXED (fixed36), raedlabel322, 176, 176);
  gtk_widget_set_size_request (raedlabel322, 57, 17);

  raedscrolledwindowcoursdisponible5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (raedscrolledwindowcoursdisponible5);
  gtk_fixed_put (GTK_FIXED (fixed36), raedscrolledwindowcoursdisponible5, 32, 240);
  gtk_widget_set_size_request (raedscrolledwindowcoursdisponible5, 600, 210);

  raedtreeview12 = gtk_tree_view_new ();
  gtk_widget_show (raedtreeview12);
  gtk_container_add (GTK_CONTAINER (raedscrolledwindowcoursdisponible5), raedtreeview12);

  raedentrycour5 = gtk_entry_new ();
  gtk_widget_show (raedentrycour5);
  gtk_fixed_put (GTK_FIXED (fixed36), raedentrycour5, 376, 136);
  gtk_widget_set_size_request (raedentrycour5, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (raedentrycour5), 8226);

  raedcheckbutton6 = gtk_check_button_new_with_mnemonic (_("professionnel"));
  gtk_widget_show (raedcheckbutton6);
  gtk_fixed_put (GTK_FIXED (fixed36), raedcheckbutton6, 408, 176);
  gtk_widget_set_size_request (raedcheckbutton6, 118, 24);

  raedcheckbutton5 = gtk_check_button_new_with_mnemonic (_("debutant"));
  gtk_widget_show (raedcheckbutton5);
  gtk_fixed_put (GTK_FIXED (fixed36), raedcheckbutton5, 272, 176);
  gtk_widget_set_size_request (raedcheckbutton5, 118, 24);

  raedcomboboxxentryspecialit__5 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (raedcomboboxxentryspecialit__5);
  gtk_fixed_put (GTK_FIXED (fixed36), raedcomboboxxentryspecialit__5, 376, 96);
  gtk_widget_set_size_request (raedcomboboxxentryspecialit__5, 173, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (raedcomboboxxentryspecialit__5), _("fitness"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (raedcomboboxxentryspecialit__5), _("yoga"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (raedcomboboxxentryspecialit__5), _("cardio "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (raedcomboboxxentryspecialit__5), _("boxe"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (raedcomboboxxentryspecialit__5), _("karate"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (raedcomboboxxentryspecialit__5), _("musculation "));

  raedbuttoninscrire5 = gtk_button_new ();
  gtk_widget_show (raedbuttoninscrire5);
  gtk_fixed_put (GTK_FIXED (fixed36), raedbuttoninscrire5, 280, 456);
  gtk_widget_set_size_request (raedbuttoninscrire5, 168, 40);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (raedbuttoninscrire5), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image41 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image41);
  gtk_box_pack_start (GTK_BOX (hbox33), image41, FALSE, FALSE, 0);

  label275 = gtk_label_new_with_mnemonic (_("inscrire"));
  gtk_widget_show (label275);
  gtk_box_pack_start (GTK_BOX (hbox33), label275, FALSE, FALSE, 0);

  label268 = gtk_label_new (_("inscrire a un cour"));
  gtk_widget_show (label268);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook11), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook11), 0), label268);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook11), empty_notebook_page);

  label269 = gtk_label_new (_("label269"));
  gtk_widget_show (label269);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook11), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook11), 1), label269);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook11), empty_notebook_page);

  label270 = gtk_label_new (_("label270"));
  gtk_widget_show (label270);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook11), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook11), 2), label270);

  g_signal_connect ((gpointer) raedcheckbutton6, "toggled",
                    G_CALLBACK (on_raedcheckbutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) raedcheckbutton5, "toggled",
                    G_CALLBACK (on_raedcheckbutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) raedbuttoninscrire5, "clicked",
                    G_CALLBACK (on_raedbuttoninscrire5_clicked),
                    NULL);
  g_signal_connect ((gpointer) alignment33, "clicked",
                    G_CALLBACK (on_alignment33_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (RaedWindowMembre, RaedWindowMembre, "RaedWindowMembre");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, notebook11, "notebook11");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, fixed36, "fixed36");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, raedentrycentre5, "raedentrycentre5");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, raedlabelbienvenue5, "raedlabelbienvenue5");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, raedlabelcoursdisponible5, "raedlabelcoursdisponible5");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, raedlabelcentre5, "raedlabelcentre5");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, raedlabelcour5, "raedlabelcour5");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, raedlabelspecialit__5, "raedlabelspecialit__5");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, raedlabel322, "raedlabel322");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, raedscrolledwindowcoursdisponible5, "raedscrolledwindowcoursdisponible5");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, raedtreeview12, "raedtreeview12");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, raedentrycour5, "raedentrycour5");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, raedcheckbutton6, "raedcheckbutton6");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, raedcheckbutton5, "raedcheckbutton5");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, raedcomboboxxentryspecialit__5, "raedcomboboxxentryspecialit__5");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, raedbuttoninscrire5, "raedbuttoninscrire5");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, image41, "image41");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, label275, "label275");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, label268, "label268");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, label269, "label269");
  GLADE_HOOKUP_OBJECT (RaedWindowMembre, label270, "label270");

  return RaedWindowMembre;
}

GtkWidget*
create_MalekMhatliWindInscritCours (void)
{
  GtkWidget *MalekMhatliWindInscritCours;
  GtkWidget *fixed37;
  GtkWidget *treeview13;
  GtkWidget *button47;
  GtkWidget *alignment34;
  GtkWidget *hbox34;
  GtkWidget *image42;
  GtkWidget *label277;
  GtkObject *spinbutton34_adj;
  GtkWidget *spinbutton34;
  GtkObject *spinbutton35_adj;
  GtkWidget *spinbutton35;
  GtkObject *spinbutton36_adj;
  GtkWidget *spinbutton36;
  GtkObject *spinbutton37_adj;
  GtkWidget *spinbutton37;
  GtkWidget *label278;
  GtkWidget *label279;
  GtkWidget *label280;
  GtkWidget *button48;
  GtkWidget *alignment35;
  GtkWidget *hbox35;
  GtkWidget *image43;
  GtkWidget *label281;
  GtkWidget *comboboxentry10;

  MalekMhatliWindInscritCours = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MalekMhatliWindInscritCours), _("S'inscrire \303\240 un Cours"));

  fixed37 = gtk_fixed_new ();
  gtk_widget_show (fixed37);
  gtk_container_add (GTK_CONTAINER (MalekMhatliWindInscritCours), fixed37);

  treeview13 = gtk_tree_view_new ();
  gtk_widget_show (treeview13);
  gtk_fixed_put (GTK_FIXED (fixed37), treeview13, 24, 24);
  gtk_widget_set_size_request (treeview13, 472, 368);

  button47 = gtk_button_new ();
  gtk_widget_show (button47);
  gtk_fixed_put (GTK_FIXED (fixed37), button47, 200, 424);
  gtk_widget_set_size_request (button47, 160, 48);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (button47), alignment34);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox34);

  image42 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image42);
  gtk_box_pack_start (GTK_BOX (hbox34), image42, FALSE, FALSE, 0);

  label277 = gtk_label_new_with_mnemonic (_("D\303\251connexion"));
  gtk_widget_show (label277);
  gtk_box_pack_start (GTK_BOX (hbox34), label277, FALSE, FALSE, 0);

  spinbutton34_adj = gtk_adjustment_new (10, 0, 31, 1, 10, 10);
  spinbutton34 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton34_adj), 1, 0);
  gtk_widget_show (spinbutton34);
  gtk_fixed_put (GTK_FIXED (fixed37), spinbutton34, 504, 120);
  gtk_widget_set_size_request (spinbutton34, 60, 27);

  spinbutton35_adj = gtk_adjustment_new (11, 0, 12, 1, 10, 10);
  spinbutton35 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton35_adj), 1, 0);
  gtk_widget_show (spinbutton35);
  gtk_fixed_put (GTK_FIXED (fixed37), spinbutton35, 584, 120);
  gtk_widget_set_size_request (spinbutton35, 60, 27);

  spinbutton36_adj = gtk_adjustment_new (2025, 0, 2030, 1, 10, 10);
  spinbutton36 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton36_adj), 1, 0);
  gtk_widget_show (spinbutton36);
  gtk_fixed_put (GTK_FIXED (fixed37), spinbutton36, 664, 120);
  gtk_widget_set_size_request (spinbutton36, 60, 27);

  spinbutton37_adj = gtk_adjustment_new (1, 0, 30, 1, 10, 10);
  spinbutton37 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton37_adj), 1, 0);
  gtk_widget_show (spinbutton37);
  gtk_fixed_put (GTK_FIXED (fixed37), spinbutton37, 592, 368);
  gtk_widget_set_size_request (spinbutton37, 60, 27);

  label278 = gtk_label_new (_("Date de S\303\251ance :"));
  gtk_widget_show (label278);
  gtk_fixed_put (GTK_FIXED (fixed37), label278, 520, 40);
  gtk_widget_set_size_request (label278, 192, 48);

  label279 = gtk_label_new (_("Heure de S\303\251ance :"));
  gtk_widget_show (label279);
  gtk_fixed_put (GTK_FIXED (fixed37), label279, 520, 168);
  gtk_widget_set_size_request (label279, 192, 56);

  label280 = gtk_label_new (_("Nombre des memebres :"));
  gtk_widget_show (label280);
  gtk_fixed_put (GTK_FIXED (fixed37), label280, 528, 296);
  gtk_widget_set_size_request (label280, 176, 56);

  button48 = gtk_button_new ();
  gtk_widget_show (button48);
  gtk_fixed_put (GTK_FIXED (fixed37), button48, 544, 424);
  gtk_widget_set_size_request (button48, 160, 48);

  alignment35 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment35);
  gtk_container_add (GTK_CONTAINER (button48), alignment35);

  hbox35 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox35);
  gtk_container_add (GTK_CONTAINER (alignment35), hbox35);

  image43 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image43);
  gtk_box_pack_start (GTK_BOX (hbox35), image43, FALSE, FALSE, 0);

  label281 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label281);
  gtk_box_pack_start (GTK_BOX (hbox35), label281, FALSE, FALSE, 0);

  comboboxentry10 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry10);
  gtk_fixed_put (GTK_FIXED (fixed37), comboboxentry10, 528, 240);
  gtk_widget_set_size_request (comboboxentry10, 189, 29);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MalekMhatliWindInscritCours, MalekMhatliWindInscritCours, "MalekMhatliWindInscritCours");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, fixed37, "fixed37");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, treeview13, "treeview13");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, button47, "button47");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, image42, "image42");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, label277, "label277");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, spinbutton34, "spinbutton34");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, spinbutton35, "spinbutton35");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, spinbutton36, "spinbutton36");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, spinbutton37, "spinbutton37");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, label278, "label278");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, label279, "label279");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, label280, "label280");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, button48, "button48");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, alignment35, "alignment35");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, image43, "image43");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, label281, "label281");
  GLADE_HOOKUP_OBJECT (MalekMhatliWindInscritCours, comboboxentry10, "comboboxentry10");

  return MalekMhatliWindInscritCours;
}

